module.exports = {
  apps: [{
    name: 'beer-pos',
    script: 'server.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 3000,
      HOST: '0.0.0.0',
      IS_CLOUD_SERVER: 'true',
      CLOUD_MODE: 'true',
      SESSION_SECRET: process.env.SESSION_SECRET || 'change-me-in-production',
      DISTRIBUTOR_NAME: 'BeerPOS Cloud',
      TRUST_PROXY: 'true',
      ALLOWED_ORIGIN: 'https://biatuoitayninh.store',
    },
    error_file: 'logs/err.log',
    out_file: 'logs/out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    max_memory_restart: '500M',
    autorestart: true,
    restart_delay: 4000,
    max_restarts: 10,
    exp_backoff_restart_delay: 100,
    watch: false,
    ignore_watch: [
      'node_modules',
      'logs',
      'backup',
      'public',
      'views',
      'src',
      'routes',
      'middleware',
      'database.sqlite',
      'database.sqlite-*',
      '*.log',
    ],
  }],
};
