module.exports = {
  apps: [{
    name: 'beer-pos',
    script: './server.js',
    cwd: __dirname,
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 3000,
      HOST: '0.0.0.0',
      IS_CLOUD_SERVER: 'true',
      CLOUD_MODE: 'true',
      SESSION_SECRET: process.env.SESSION_SECRET || 'change-me-to-a-long-random-string-in-production',
      DISTRIBUTOR_NAME: 'BeerPOS Cloud',
      TRUST_PROXY: 'true',
      ALLOWED_ORIGIN: '*',
      CLOUD_DOMAIN: 'http://103.75.183.57:3000',
      ADMIN_DOMAIN: '103.75.183.57',
      PUBLIC_DOMAIN: '103.75.183.57',
      GITHUB_WEBHOOK_SECRET: '8d5780a20a06427187c3e6cebf0b92078b929b4b0d97a2f9bdf83208a3151fd6',
    },
    error_file: './logs/err.log',
    out_file: './logs/out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    merge_logs: true,
    max_memory_restart: '500M',
    autorestart: true,
    restart_delay: 4000,
    max_restarts: 10,
    exp_backoff_restart_delay: 100,
    watch: false,
    ignore_watch: [
      'node_modules',
      'logs',
      'backup',
      'public',
      'views',
      'src',
      'routes',
      'middleware',
      'database.sqlite',
      'database.sqlite-*',
      '*.log',
    ],
  }],
};
